[package]
name = "toolbox"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.96"
dotenvy = "0.15.7"
mongodb = { version = "2.5.0", features = ["tokio-sync"] }
